import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lock_in/data/models/group_model.dart';
import 'package:lock_in/data/models/group_member_model.dart';
import 'package:lock_in/data/models/group_goal_model.dart';

// Dummy data providers for testing
final dummyGroupsProvider = Provider<List<GroupModel>>((ref) {
  return [
    GroupModel(
      id: '1',
      name: 'Study Squad 📚',
      description: 'Daily study group for computer science students. Let\'s ace those exams together!',
      creatorId: 'user1',
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now(),
      privacy: GroupPrivacy.public,
      memberCount: 12,
      totalGoalsCompleted: 45,
      totalStudyTime: 180,
      inviteCode: 'STUDY123',
      categories: ['Study', 'Programming', 'Computer Science'],
    ),
    GroupModel(
      id: '2',
      name: 'Productivity Masters 🚀',
      description: 'Focus on building better habits and crushing goals. No distractions allowed!',
      creatorId: 'user2',
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now(),
      privacy: GroupPrivacy.public,
      memberCount: 8,
      totalGoalsCompleted: 28,
      totalStudyTime: 120,
      inviteCode: 'PROD456',
      categories: ['Productivity', 'Habits'],
    ),
    GroupModel(
      id: '3',
      name: 'Early Birds Club 🌅',
      description: 'Wake up early, study hard, achieve more. Morning study sessions from 5-7 AM.',
      creatorId: 'user1',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      updatedAt: DateTime.now(),
      privacy: GroupPrivacy.public,
      memberCount: 15,
      totalGoalsCompleted: 60,
      totalStudyTime: 240,
      inviteCode: 'EARLY789',
      categories: ['Study', 'Morning Routine'],
    ),
    GroupModel(
      id: '4',
      name: 'Code Warriors 💻',
      description: 'Learn, code, repeat. Join us for daily coding challenges and pair programming.',
      creatorId: 'user3',
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
      updatedAt: DateTime.now(),
      privacy: GroupPrivacy.private,
      requiresApproval: true,
      memberCount: 20,
      totalGoalsCompleted: 95,
      totalStudyTime: 450,
      inviteCode: 'CODE2024',
      categories: ['Programming', 'Learning'],
    ),
    GroupModel(
      id: '5',
      name: 'Exam Prep 2025 📝',
      description: 'Final exam preparation group. Sharing notes, resources, and motivation!',
      creatorId: 'user2',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now(),
      privacy: GroupPrivacy.public,
      memberCount: 25,
      totalGoalsCompleted: 35,
      totalStudyTime: 200,
      inviteCode: 'EXAM2025',
      categories: ['Study', 'Exam Prep'],
    ),
  ];
});

final dummyMembersProvider = Provider.family<List<GroupMemberModel>, String>((ref, groupId) {
  return [
    GroupMemberModel(
      userId: 'user1',
      groupId: groupId,
      displayName: 'Alex Johnson',
      email: 'alex@example.com',
      role: MemberRole.admin,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 30)),
      approvedAt: DateTime.now().subtract(const Duration(days: 30)),
      goalsCompleted: 15,
      studyTime: 450,
      currentStreak: 12,
      longestStreak: 18,
    ),
    GroupMemberModel(
      userId: 'user2',
      groupId: groupId,
      displayName: 'Sarah Williams',
      email: 'sarah@example.com',
      role: MemberRole.moderator,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 25)),
      approvedAt: DateTime.now().subtract(const Duration(days: 25)),
      goalsCompleted: 12,
      studyTime: 380,
      currentStreak: 8,
      longestStreak: 15,
    ),
    GroupMemberModel(
      userId: 'user3',
      groupId: groupId,
      displayName: 'Mike Chen',
      email: 'mike@example.com',
      role: MemberRole.member,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 20)),
      approvedAt: DateTime.now().subtract(const Duration(days: 20)),
      goalsCompleted: 10,
      studyTime: 320,
      currentStreak: 10,
      longestStreak: 12,
    ),
    GroupMemberModel(
      userId: 'user4',
      groupId: groupId,
      displayName: 'Emma Davis',
      email: 'emma@example.com',
      role: MemberRole.member,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 15)),
      approvedAt: DateTime.now().subtract(const Duration(days: 15)),
      goalsCompleted: 8,
      studyTime: 280,
      currentStreak: 7,
      longestStreak: 10,
    ),
    GroupMemberModel(
      userId: 'user5',
      groupId: groupId,
      displayName: 'James Wilson',
      email: 'james@example.com',
      role: MemberRole.member,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 10)),
      approvedAt: DateTime.now().subtract(const Duration(days: 10)),
      goalsCompleted: 5,
      studyTime: 180,
      currentStreak: 5,
      longestStreak: 8,
    ),
  ];
});

final dummyGoalsProvider = Provider.family<List<GroupGoalModel>, String>((ref, groupId) {
  return [
    GroupGoalModel(
      id: 'goal1',
      groupId: groupId,
      title: 'Study 2 Hours Daily',
      description: 'Complete at least 2 hours of focused study every day this week.',
      createdBy: 'user1',
      createdByName: 'Alex Johnson',
      type: GoalType.daily,
      status: GoalStatus.inProgress,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      startDate: DateTime.now().subtract(const Duration(days: 2)),
      endDate: DateTime.now().add(const Duration(days: 5)),
      targetMinutes: 840, // 7 days * 120 minutes
      completedMinutes: 480, // 4 days completed
      isShared: true,
      completedByUserIds: ['user1', 'user2', 'user3'],
    ),
    GroupGoalModel(
      id: 'goal2',
      groupId: groupId,
      title: 'Complete 5 Practice Sessions',
      description: 'Finish at least 5 focused study sessions this week.',
      createdBy: 'user2',
      createdByName: 'Sarah Williams',
      type: GoalType.weekly,
      status: GoalStatus.inProgress,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      startDate: DateTime.now().subtract(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 4)),
      targetSessions: 5,
      completedSessions: 3,
      isShared: true,
      isCompetitive: true,
      completedByUserIds: ['user1', 'user2'],
    ),
    GroupGoalModel(
      id: 'goal3',
      groupId: groupId,
      title: 'Master Data Structures',
      description: 'Study and practice all major data structures topics.',
      createdBy: 'user1',
      createdByName: 'Alex Johnson',
      type: GoalType.monthly,
      status: GoalStatus.inProgress,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      startDate: DateTime.now().subtract(const Duration(days: 10)),
      endDate: DateTime.now().add(const Duration(days: 20)),
      targetMinutes: 1200,
      completedMinutes: 450,
      isShared: true,
      completedByUserIds: ['user1'],
    ),
    GroupGoalModel(
      id: 'goal4',
      groupId: groupId,
      title: 'No Social Media Week',
      description: 'Stay off social media for 7 days straight.',
      createdBy: 'user3',
      createdByName: 'Mike Chen',
      type: GoalType.weekly,
      status: GoalStatus.completed,
      createdAt: DateTime.now().subtract(const Duration(days: 14)),
      startDate: DateTime.now().subtract(const Duration(days: 14)),
      endDate: DateTime.now().subtract(const Duration(days: 7)),
      targetSessions: 7,
      completedSessions: 7,
      isShared: true,
      completedByUserIds: ['user1', 'user2', 'user3', 'user4'],
    ),
  ];
});

// Simple providers that return all members/goals (not filtered by groupId)
final allDummyMembersProvider = Provider<List<GroupMemberModel>>((ref) {
  return [
    GroupMemberModel(
      userId: 'user1',
      groupId: '1',
      displayName: 'Alex Johnson',
      email: 'alex@example.com',
      role: MemberRole.admin,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 30)),
      approvedAt: DateTime.now().subtract(const Duration(days: 30)),
      goalsCompleted: 15,
      studyTime: 450,
      currentStreak: 12,
      longestStreak: 18,
    ),
    GroupMemberModel(
      userId: 'user2',
      groupId: '1',
      displayName: 'Sarah Williams',
      email: 'sarah@example.com',
      role: MemberRole.moderator,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 25)),
      approvedAt: DateTime.now().subtract(const Duration(days: 25)),
      goalsCompleted: 12,
      studyTime: 380,
      currentStreak: 8,
      longestStreak: 15,
    ),
    GroupMemberModel(
      userId: 'user3',
      groupId: '1',
      displayName: 'Mike Chen',
      email: 'mike@example.com',
      role: MemberRole.member,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 20)),
      approvedAt: DateTime.now().subtract(const Duration(days: 20)),
      goalsCompleted: 10,
      studyTime: 320,
      currentStreak: 10,
      longestStreak: 12,
    ),
    GroupMemberModel(
      userId: 'user4',
      groupId: '1',
      displayName: 'Emma Davis',
      email: 'emma@example.com',
      role: MemberRole.member,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 15)),
      approvedAt: DateTime.now().subtract(const Duration(days: 15)),
      goalsCompleted: 8,
      studyTime: 280,
      currentStreak: 7,
      longestStreak: 10,
    ),
    GroupMemberModel(
      userId: 'user5',
      groupId: '1',
      displayName: 'James Wilson',
      email: 'james@example.com',
      role: MemberRole.member,
      status: MemberStatus.active,
      joinedAt: DateTime.now().subtract(const Duration(days: 10)),
      approvedAt: DateTime.now().subtract(const Duration(days: 10)),
      goalsCompleted: 5,
      studyTime: 200,
      currentStreak: 5,
      longestStreak: 8,
    ),
  ];
});

final allDummyGoalsProvider = Provider<List<GroupGoalModel>>((ref) {
  return [
    GroupGoalModel(
      id: 'goal1',
      groupId: '1',
      title: 'Study 2 Hours Daily',
      description: 'Complete at least 2 hours of focused study every day this week.',
      createdBy: 'user1',
      createdByName: 'Alex Johnson',
      type: GoalType.daily,
      status: GoalStatus.inProgress,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      startDate: DateTime.now().subtract(const Duration(days: 2)),
      endDate: DateTime.now().add(const Duration(days: 5)),
      targetMinutes: 840,
      completedMinutes: 480,
      isShared: true,
      completedByUserIds: ['user1', 'user2', 'user3'],
    ),
    GroupGoalModel(
      id: 'goal2',
      groupId: '1',
      title: 'Complete 5 Practice Sessions',
      description: 'Finish at least 5 focused study sessions this week.',
      createdBy: 'user2',
      createdByName: 'Sarah Williams',
      type: GoalType.weekly,
      status: GoalStatus.inProgress,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      startDate: DateTime.now().subtract(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 4)),
      targetSessions: 5,
      completedSessions: 3,
      isShared: true,
      isCompetitive: true,
      completedByUserIds: ['user1', 'user2'],
    ),
    GroupGoalModel(
      id: 'goal3',
      groupId: '1',
      title: 'Master Data Structures',
      description: 'Study and practice all major data structures topics.',
      createdBy: 'user1',
      createdByName: 'Alex Johnson',
      type: GoalType.monthly,
      status: GoalStatus.inProgress,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      startDate: DateTime.now().subtract(const Duration(days: 5)),
      endDate: DateTime.now().add(const Duration(days: 25)),
      targetSessions: 20,
      completedSessions: 6,
      isShared: true,
      completedByUserIds: ['user1'],
    ),
    GroupGoalModel(
      id: 'goal4',
      groupId: '1',
      title: 'Morning Study Streak',
      description: 'Study every morning for 7 days straight.',
      createdBy: 'user3',
      createdByName: 'Mike Chen',
      type: GoalType.custom,
      status: GoalStatus.completed,
      createdAt: DateTime.now().subtract(const Duration(days: 14)),
      startDate: DateTime.now().subtract(const Duration(days: 14)),
      endDate: DateTime.now().subtract(const Duration(days: 7)),
      targetSessions: 7,
      completedSessions: 7,
      isShared: true,
      completedByUserIds: ['user1', 'user2', 'user3', 'user4'],
    ),
  ];
});

// Use dummy data for development
final useRealDataProvider = Provider<bool>((ref) => false);
